CREATE OR REPLACE PACKAGE BODY HR_PAYROLL AS
   v_tax_rate NUMBER := 0.15;
   
   PROCEDURE PROCESS_SALARY IS
   BEGIN
      INSERT INTO PAYROLL_LOG (EMP_ID, NET_SALARY)
      SELECT EMP_ID, GROSS_SALARY - (GROSS_SALARY * v_tax_rate) AS NET_SALARY
      FROM EMP_TABLE;
   END PROCESS_SALARY;
END HR_PAYROLL;