CREATE OR REPLACE PACKAGE BODY HR_UTILS AS
    PROCEDURE PROCESS_ANNUAL_INCREMENT(p_dept_id NUMBER, p_percent NUMBER) IS
    BEGIN
        INSERT INTO SALARY_HISTORY (EMP_ID, OLD_SALARY, NEW_SALARY, CHANGE_DATE)
        SELECT e.EMP_ID, e.SALARY, e.SALARY * (1 + p_percent/100), SYSDATE
        FROM EMPLOYEES e
        WHERE e.DEPARTMENT_ID = p_dept_id;

        UPDATE EMPLOYEES
        SET SALARY = SALARY * (1 + p_percent/100)
        WHERE DEPARTMENT_ID = p_dept_id;
    END PROCESS_ANNUAL_INCREMENT;
END HR_UTILS;